"""add filename&url

Revision ID: 00db6cecfd58
Revises: 1f9532113731
Create Date: 2019-10-25 09:27:48.624324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00db6cecfd58'
down_revision = '1f9532113731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('bladed_filename', sa.String(length=128), nullable=True))
    op.add_column('task', sa.Column('bladed_url', sa.String(length=256), nullable=True))
    op.add_column('task', sa.Column('xml_filename', sa.String(length=128), nullable=True))
    op.add_column('task', sa.Column('xml_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'xml_url')
    op.drop_column('task', 'xml_filename')
    op.drop_column('task', 'bladed_url')
    op.drop_column('task', 'bladed_filename')
    # ### end Alembic commands ###
