"""add bladed_version in Task

Revision ID: 1f9532113731
Revises: 06efc6dc4cf6
Create Date: 2019-10-06 20:45:16.384826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9532113731'
down_revision = '06efc6dc4cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('bladed_version', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'bladed_version')
    # ### end Alembic commands ###
