"""initial

Revision ID: 5269d5becaa7
Revises: 
Create Date: 2019-11-14 16:42:27.621673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5269d5becaa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=True),
    sa.Column('realname', sa.String(length=24), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('date_stamp', sa.DateTime(), nullable=True),
    sa.Column('bladed_version', sa.String(length=8), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bladed_filename', sa.String(length=128), nullable=True),
    sa.Column('bladed_url', sa.String(length=256), nullable=True),
    sa.Column('xml_filename', sa.String(length=128), nullable=True),
    sa.Column('xml_url', sa.String(length=256), nullable=True),
    sa.Column('symbol_index', sa.Integer(), nullable=True),
    sa.Column('symbol_filename', sa.String(length=128), nullable=True),
    sa.Column('symbol_url', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_task_date_stamp'), 'task', ['date_stamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_date_stamp'), table_name='task')
    op.drop_table('task')
    op.drop_table('user')
    # ### end Alembic commands ###
