'''
@Descripttion: 
@version: 
@Author: wangshiwen@36719
@Date: 2020-01-02 16:14:43
@LastEditors  : wangshiwen@36719
@LastEditTime : 2020-01-02 16:58:55
'''
"""修改上传方式

Revision ID: 9c88c0bc500f
Revises: f4c9dd3413ed
Create Date: 2020-01-02 16:14:43.525524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c88c0bc500f'
down_revision = 'f4c9dd3413ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('controller_src', sa.String(length=256), nullable=True))
    op.add_column('task', sa.Column('dll_filename', sa.String(length=128), nullable=True))
    with op.batch_alter_table('task') as batch_op:
        batch_op.drop_column('xml_url')
        batch_op.drop_column('symbol_url')
        batch_op.drop_column('bladed_url')
        batch_op.drop_column('symbol_filename')
        batch_op.drop_column('symbol_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('symbol_index', sa.INTEGER(), nullable=True))
    op.add_column('task', sa.Column('symbol_filename', sa.VARCHAR(length=128), nullable=True))
    op.add_column('task', sa.Column('bladed_url', sa.VARCHAR(length=256), nullable=True))
    op.add_column('task', sa.Column('symbol_url', sa.VARCHAR(length=256), nullable=True))
    op.add_column('task', sa.Column('xml_url', sa.VARCHAR(length=256), nullable=True))
    with op.batch_alter_table('task') as batch_op:
        batch_op.drop_column('dll_filename')
        batch_op.drop_column('controller_src')
    # ### end Alembic commands ###
