"""add realname

Revision ID: a505d63c7b7f
Revises: b931e07d1780
Create Date: 2019-10-05 21:42:16.262726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a505d63c7b7f'
down_revision = 'b931e07d1780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('realname', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'realname')
    # ### end Alembic commands ###
