"""add symbol-index

Revision ID: a904a873465d
Revises: 00db6cecfd58
Create Date: 2019-10-25 17:40:16.942993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a904a873465d'
down_revision = '00db6cecfd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('symbol_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'symbol_index')
    # ### end Alembic commands ###
