"""add symbol-url

Revision ID: c989e1a8ff81
Revises: a904a873465d
Create Date: 2019-10-26 11:20:38.434267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c989e1a8ff81'
down_revision = 'a904a873465d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('symbol_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'symbol_url')
    # ### end Alembic commands ###
